version: '3.8'

services:
  crm-backend-consign:
    container_name: crm-backend-consign
    restart: always
    build:
      context: .
      target: dependencies
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    command: dumb-init node ace serve --watch
    networks:
      - aws

networks:
  aws:
    driver: bridge
